// react/src/components/04-Accordion/Accordion.tsx
import { useState } from 'react';

interface AccordionProps {
  title: string,
  contents: string
}

function Accordion({ title, contents }: AccordionProps) {

  const [collapsed, setCollapsed] = useState(false);

  return (
    <div>
      <button onClick={() => setCollapsed(!collapsed)}>{title}</button>
      {collapsed ? <p>{contents}</p> : null}
    </div>
  );
}

export default Accordion;

// vue/src/components/04-Accordion/Accordion.vue
<template>
  <div>
    <button @click="collapsed = !collapsed" class="title">{{ title }}</button>
    <p v-show="!collapsed" class="contents">{{ contents }}</p>
  </div>
</template>

<script setup lang='ts'>
import { ref } from 'vue';

const collapsed = ref(true);

const props = defineProps<{
  title: string
  contents: number
}>()
</script>
