// react/src/components/02-ContactForm/ContactForm.tsx
import { useState } from 'react';

function ContactForm() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    message: "",
  })

  const submit = (e: any) => {
    e.preventDefault()
    console.log(formData)
  }

  return (
    <div>
      <h2>02. Contact Form</h2>
      <form method="post" onSubmit={submit}>
        <div>
          <label htmlFor="name">Name </label>
          <input
            onChange={(e) => setFormData({ ...formData, name: e.target.value })}
            type="text"
            id="name"
            name="name"
            placeholder="Name"
            value={formData.name} />
        </div>
        <div>
          <label htmlFor="email">Email </label>
          <input
            onChange={(e) => setFormData({ ...formData, email: e.target.value })}
            type="text"
            id="email"
            name="email"
            placeholder="Email"
            value={formData.email} />
        </div>
        <div>
          <label htmlFor="message">Message </label>
          <textarea
            onChange={(e) => setFormData({ ...formData, message: e.target.value })}
            id="message"
            name="message"
            value={formData.message}></textarea>
        </div>
        <button
          type="submit">Send</button>
      </form>
    </div>
  );
}

export default ContactForm;

// vue/src/components/02-ContactForm/ContactForm.vue
<script setup lang="ts">
import { reactive } from 'vue';

const formData = reactive({
  name: '',
  email: '',
  message: '',
})

const submit = () => {
  console.log(formData)
}

</script>
<template>
  <h2>02. Contact Form</h2>
  <form method="post" @submit.prevent="submit">
    <div>
      <label for="name">Name </label>
      <input type="text" id="name" name="name" placeholder="Name" v-model="formData.name" />
    </div>
    <div>
      <label for="email">Email </label>
      <input type="text" id="email" name="email" placeholder="Email" v-model="formData.email" />
    </div>
    <div>
      <label for="message">Message </label>
      <textarea id="message" name="message" v-model="formData.message"></textarea>
    </div>
    <button type="submit">Send</button>
  </form>
</template>
